name: Build base images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * 6"

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: hub.docker.com
  IMAGE_REPO: sahistory

jobs:
  build_nginx:
    name: Build nginx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build nginx
        run: |
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}/nginx:latest"
          docker buildx build \
            --tag $IMAGE_NAME \
            --platform linux/amd64,linux/arm64 \
            -f nginx.Dockerfile \
            --push \
            .

  build_jobs:
    name: Build jobs container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build jobs
        run: |
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}/jobs:latest"
          docker buildx build \
            --tag $IMAGE_NAME \
            --platform linux/amd64,linux/arm64 \
            --build-arg PHP_VERSION=7.4 \
            --push \
            -f jobs.Dockerfile \
            .

  build_fpm:
    name: Build FPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build php-fpm
        run: |
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}/phpfpm:latest"
          docker buildx build \
            --tag $IMAGE_NAME \
            --platform linux/amd64,linux/arm64 \
            --build-arg PHP_VERSION=7.4 \
            --push \
            -f php.Dockerfile \
            .
